### ISSUE TITLE
IDocumentClient interface does not expose ReadDocumentAsync<T> that DocumentClient class offers

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-documentdb-dotnet#227]
The `IDocumentClient` interface does not currently expose the `ReadDocumentAsync<T>` methods that are offered by the `DocumentClient` class. These overloads would be useful and, AFAICT, far more efficient than having to use LINQ based querying API for reading single document instances into the exact type `T` that we need. The interface does expose the non-generic `ReadDocumentAsync` methods, so this just looks like an oversight.

I don't want to have to sacrifice using the `IDocumentClient` interface to get this functionality as I've found it extremely useful to be able to rely on the abstraction that the interface provides for the purposes of mocking while unit testing my repository layer.

**Comment by nonnb** [comment]
I believe there are additional missing interface methods, such as `CreateDatabaseIfNotExistsAsync`. Seemingly at present, we to hack by downcasting the interface to access the method

**Comment by takekazuomi** [comment]
+1  CreateDocumentCollectionIfNotExistsAsync too.

**Comment by ryandle** [comment]
All of the IfNotExistsAsync methods are missing, would be great to have the full public API on DocumentClient added to IDocumentClient for easier mocking.

**Comment by surenderssm** [comment]
is there any ETA for this ?

**Comment by surenderssm** [comment]
CreateDocumentCollectionIfNotExistsAsync is also one of the missing action!

**Comment by mgiannikouris** [comment]
+1 would like to see ReadDocumentAsync<T> in the interface if possible (also create if not exists).

**Comment by tariknz** [comment]
Yeah its a little weird because we're supposed to create a singleton of the client accross your application, yet we can't effectively use the IDocumentClient provided without doing some hacky casting. Hopefully it is resolved soon.

**Comment by connor4312** [comment]
Any news on this?

**Comment by MovGP0** [comment]
there is another issue: `IDocumentQuery` and `IDocumentQuery<T>` do not derive from `IQueryable` and `IQueryable<T>`, while their implementations do. This causes not only additional typecasting, but also makes unit testing much harder.

**Comment by vinoddamupatil** [comment]
As per following this method is available:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.readdocumentasync?view=azure-dotnet#Applies_to

But still not found while i had installed latest  package Microsoft.Azure.DocumentDB 1.20.0

**Comment by takekazuomi** [comment]
@AdrianSanguineti 
Open source Microsoft's plan for DocumentDB Client .NET SDK is uncertain.
This feedback has no answer.
https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/18902368-opensource-documentdb-net-sdk

**Comment by AdrianSanguineti** [comment]
`OpenAsync()` is another method not defined on the `IDocumentClient` interface, even in the 2.0.0-preview package. 

The Performance Tips article recommends calling it to avoid startup latency: https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips

**Comment by aaronhoffman** [comment]
For `ReadDocumentAsync<T>`, might try this workaround:

```
var document = await _documentClient.ReadDocumentAsync(documentUri);
TResource res = (dynamic)document.Resource;
```
