### ISSUE TITLE
Transient exception in GenerateKeyAuthorizationSignature

### ISSUE THREAD

**Issue by johnstairs** [Azure/azure-documentdb-dotnet#463]
Hi, we see in our logs that we got follwoing exception, twice in a three-second span, and then have not seen it since. So not a high-severity issue. We are using direct connectivity with tcp and using resource tokens. The error would **not** have happened on the first usage of a DocumentClient instance: the instance would already have been opened and validated before reaching this point. 

Not sure how actionable this is for you, but perhaps there is a subtle issue somewhere, either in our code or yours.

We are using Microsoft.Azure.DocumentDB.Core, version 1.7.1.

```
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.Azure.Documents.AuthorizationHelper.GenerateKeyAuthorizationSignature(String verb, String resourceId, String resourceType, NameValueCollection headers, String key, Boolean bUseUtcNowForMissingXDate)
   at Microsoft.Azure.Documents.AuthorizationHelper.GenerateKeyAuthorizationSignature(String verb, Uri uri, NameValueCollection headers, String key, String clientVersion)
   at Microsoft.Azure.Documents.Client.DocumentClient.<GetDatabaseAccountPrivateAsync>d__261.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Routing.GlobalEndpointManager.<GetDatabaseAccountFromAnyLocationsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Routing.GlobalEndpointManager.<RefreshLocationAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.ClientRetryPolicy.<ShouldRetryOnEndpointFailureAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.ClientRetryPolicy.<ShouldRetryAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.PartitionKeyRangeGoneRetryPolicy.<ShouldRetryAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<ExecuteInternalAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<ExecuteNextAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Health.Fhir.CosmosDb.Features.Storage.DocumentClientExtensions.<PerformNoninvasiveQuery>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Health.Fhir.CosmosDb.Features.Health.CosmosHealthCheck.<CheckAsync>d__4.MoveNext()
```

**Comment by thomaslevesque** [comment]
I'm seeing exactly the same error (with Microsoft.Azure.DocumentDB.Core, version 1.9.1). Running on netcoreapp2.0.

> Please validate the account key.

That's not the problem. The account key is fine, since most queries work; as the OP said, the error is transient.

In my case I'm using resource tokens; I don't know if it's related.

**Comment by thomaslevesque** [comment]
Some additional information:
- I can't reproduce the issue locally (whether in release or debug, with the debugger attached or not); it only happens when the app is deployed in Azure.
- it happens much more frequently when I make several requests in parallel
- there's often a long delay before the exception is thrown; most requests are fast, but the ones that fail are very slow.

**Comment by thomaslevesque** [comment]
@kirankumarkolli any news on this?

@johnstairs have you been able to solve the problem?

**Comment by thomaslevesque** [comment]
> @thomaslevesque are you using resoruce tokens or key's from portal?

Both. I create a client with the portal key, use it to retrieve a permission for a given user, and use the resource token from the permission to create another client that can only access a specific partition. As far as I can tell, all failing requests are using resource tokens.

> Key is always based 64 encoded and code is validating the same. If this happens all the calls from that documentclient should fail.

> Is it recovering afterwards?

No, it isn't. I tried adding retry logic around the DocumentClient calls, but it didn't help. I guess once the client is broken, it stays broken.

> How many documentclient instances does your application create?

Many... Two for each HTTP request handled by my app.

**Comment by thomaslevesque** [comment]
OK, I think I got something. The actual source code for `DocumentClient` isn't public (yet?), but using dotPeek I managed to see what was going on.

Very simple repro of the problem : create a client with a (single) resource token, and call `GetDatabaseAccountAsync` on it.

The problem is that `GetDatabaseAccountPrivateAsync` passes the resource token to `AuthorizationHelper.GenerateKeyAuthorizationSignature`, which ends up trying to `Convert.FromBase64String` the resource token. But the resource token is not a base64 string, it's a query string, so it fails.

`GetDatabaseAccountPrivateAsync` is being called (indirectly) by `ShouldRetryOnEndpointFailureAsync`, which explains why the issue seemed to be intermittent.

**Comment by thomaslevesque** [comment]
> Documentclient is thread-safe and recommended practice is to have singleton. Singleton will get connection pooling and improves performance.

Well, in my scenario I can have the "main" `DocumentClient` as a singleton, but since I'm also using other `DocumentClient`s with short-lived resource tokens, it's not an option for those. I guess I could cache them while the token is valid. Anyway, it might improve performance, but it won't solve this problem.

> If all the failures are with ResoruceToken, If possible can you please share a repro with the sample configured resource tokens (expired ones will do).

Well, as I said earlier, the repro is fairly simple:

> Very simple repro of the problem : create a client with a (single) resource token, and call `GetDatabaseAccountAsync` on it.

I'll send a sample project shortly.

**Comment by thomaslevesque** [comment]
> can you please share a repro with the sample configured resource tokens (expired ones will do).

In fact, the repro won't work with an expired token. It gives a different error (_The authorization token is not valid at the current time_). So you need a valid token, but:
- the maximum lifetime for a token is 5 hours, so you might not have time to confirm the repro on your side
- I don't want to post a valid token for my db publicly on Github

So instead I'm sharing a repro where you can just change the account endpoint and auth key to use a CosmosDB account of your own.
[ReproCosmosResourceTokenBug.zip](https://github.com/Azure/azure-documentdb-dotnet/files/2021903/ReproCosmosResourceTokenBug.zip)

**Comment by thomaslevesque** [comment]
@kirankumarkolli have you been able to see the problem using my repro ?

**Comment by kirankumarkolli** [comment]
@thomaslevesque am able to repro the issue and fix will be included in 2.0 release (June).

ResoruceTokens are scoped to a single collection and in this specific case account information is requested with resource token. As a work-around can you please use the primary key clients while addressing non-collection resources? 

ResoruceTokens default lifetime is 4 hours but you can also request upto 24 hours of lifetime through [ReadPermission](https://msdn.microsoft.com/en-us/library/dn781778.aspx) API using RequestOptions.ResourceTokenExpirySeconds.

**Comment by thomaslevesque** [comment]
> As a work-around can you please use the primary key clients while addressing non-collection resources?

Yes, we'll do that until the fix is available.

Thanks @kirankumarkolli!

**Comment by thomaslevesque** [comment]
By the way @kirankumarkolli, would you please let me know on this thread when 2.0 is released? I'm working on a SaaS product that is supposed to go live by the end of June, and I'd like to include the fix.

**Comment by johnstairs** [comment]
@kirankumarkolli, I have another consistent repo:
1. Create a DocumentClient instance against a multi-region account using a resource token.
2. Perform a manual write region failover to another region.
3. Perform a write with the DocumentClient instance and you will get this exception. The instance is no longer usable.

**Comment by thomaslevesque** [comment]
This problem appears to be fixed in 2.0.0. The issue should be closed.

**Comment by Dervanil** [comment]
I'm using almost the same cenario as described above, and still have the same error in SDK version 2.4.0.
